# Generated by Django 6.0.2 on 2026-02-17 01:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=2)),
                ('timezone', models.CharField(max_length=100)),
                ('popularity_score', models.IntegerField(default=0, help_text='Score from 0-100 indicating city popularity', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tourist_attractions_count', models.PositiveIntegerField(default=0)),
                ('average_stay_days', models.PositiveIntegerField(default=2, help_text='Recommended days to spend in this city')),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'db_table': 'cities',
                'ordering': ['-popularity_score', 'name'],
                'indexes': [models.Index(fields=['country', 'name'], name='cities_country_6ba899_idx'), models.Index(fields=['-popularity_score'], name='cities_popular_65c8a2_idx'), models.Index(fields=['is_active', '-popularity_score'], name='cities_is_acti_85845d_idx')],
            },
        ),
        migrations.CreateModel(
            name='CityPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='Direct distance in kilometers', max_digits=8)),
                ('min_travel_hours', models.DecimalField(decimal_places=2, help_text='Minimum travel time in hours', max_digits=5)),
                ('intermediate_interest_score', models.IntegerField(default=0)),
                ('has_direct_transport', models.BooleanField(default=False)),
                ('cheapest_direct_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='destinations.city')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='destinations.city')),
            ],
            options={
                'db_table': 'city_pairs',
                'indexes': [models.Index(fields=['from_city', 'to_city'], name='city_pairs_from_ci_f56cfb_idx'), models.Index(fields=['has_direct_transport'], name='city_pairs_has_dir_de4eb0_idx')],
                'unique_together': {('from_city', 'to_city')},
            },
        ),
    ]
