# Generated by Django 6.0.2 on 2026-02-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='citypair',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='citypair',
            name='city_pairs_from_ci_f56cfb_idx',
        ),
        migrations.RemoveIndex(
            model_name='citypair',
            name='city_pairs_has_dir_de4eb0_idx',
        ),
        migrations.DeleteModel(
            name='CityPair',
        ),
    ]
