# Generated by Django 6.0.2 on 2026-02-17 01:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price in EUR', max_digits=10)),
                ('currency', models.CharField(default='EUR', help_text='ISO 4217 currency code', max_length=3)),
                ('name', models.CharField(max_length=255)),
                ('accommodation_type', models.CharField(choices=[('HOTEL', 'Hotel'), ('HOSTEL', 'Hostel'), ('APARTMENT', 'Apartment'), ('GUESTHOUSE', 'Guesthouse'), ('BNB', 'Bed & Breakfast')], max_length=50)),
                ('address', models.TextField(blank=True)),
                ('neighborhood', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('star_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_breakfast', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='destinations.city')),
            ],
            options={
                'db_table': 'accommodations',
                'ordering': ['city', 'base_price'],
            },
        ),
        migrations.CreateModel(
            name='AccommodationAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('rooms_available', models.PositiveIntegerField(default=10)),
                ('override_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_records', to='accommodation.accommodation')),
            ],
            options={
                'db_table': 'accommodation_availability',
                'ordering': ['date'],
            },
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['city', 'is_active', 'base_price'], name='accommodati_city_id_5ff8fb_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['city', 'accommodation_type'], name='accommodati_city_id_58cf7a_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['-review_score'], name='accommodati_review__d0e189_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodationavailability',
            index=models.Index(fields=['accommodation', 'date', 'is_available'], name='accommodati_accommo_3677f8_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodationavailability',
            index=models.Index(fields=['date', 'is_available'], name='accommodati_date_43395c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accommodationavailability',
            unique_together={('accommodation', 'date')},
        ),
    ]
