# Generated by Django 6.0.2 on 2026-02-17 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accommodation', '0001_initial'),
        ('destinations', '0001_initial'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_days', models.PositiveIntegerField()),
                ('is_date_flexible', models.BooleanField(default=True, help_text='Whether dates are flexible or fixed')),
                ('preferred_start_date', models.DateField(blank=True, help_text='If date NOT flexible, the fixed start date', null=True)),
                ('max_intermediate_cities', models.PositiveIntegerField(default=3)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_transport_types', models.CharField(blank=True, help_text='Comma-separated transport types', max_length=255)),
                ('preferred_accommodation_types', models.CharField(blank=True, help_text='Comma-separated accommodation types', max_length=255)),
                ('session_id', models.CharField(blank=True, help_text='Guest session identifier', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_ending_here', to='destinations.city')),
                ('start_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_starting_here', to='destinations.city')),
            ],
            options={
                'db_table': 'trip_searches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimization_type', models.CharField(choices=[('CHEAPEST', 'Lowest Total Cost'), ('FASTEST', 'Shortest Travel Time'), ('BALANCED', 'Balance of Cost and Time'), ('SCENIC', 'Most Interesting Cities')], default='CHEAPEST', max_length=50)),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Total cost for all', max_digits=10)),
                ('total_transport_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_accommodation_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_travel_hours', models.DecimalField(decimal_places=2, help_text='Total hours in transit', max_digits=6)),
                ('cities_visited_count', models.PositiveIntegerField()),
                ('cities_visited_order', models.TextField(help_text='JSON array of city IDs in visit order')),
                ('rank', models.PositiveIntegerField(default=1)),
                ('is_recommended', models.BooleanField(default=False)),
                ('calculation_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='trips.tripsearch')),
            ],
            options={
                'db_table': 'trip_itineraries',
                'ordering': ['search', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='ItinerarySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField()),
                ('transport_date', models.DateField(blank=True, help_text='Date of transport departure', null=True)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('nights_count', models.PositiveIntegerField()),
                ('accommodation_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('segment_total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_segments', to='accommodation.accommodation')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_segments', to='destinations.city')),
                ('transport_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_segments', to='transport.transportschedule')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='trips.tripitinerary')),
            ],
            options={
                'db_table': 'itinerary_segments',
                'ordering': ['itinerary', 'sequence_number'],
                'indexes': [models.Index(fields=['itinerary', 'sequence_number'], name='itinerary_s_itinera_86ff70_idx'), models.Index(fields=['city'], name='itinerary_s_city_id_5211d3_idx'), models.Index(fields=['check_in_date', 'check_out_date'], name='itinerary_s_check_i_8c42c1_idx')],
                'unique_together': {('itinerary', 'sequence_number')},
            },
        ),
        migrations.AddIndex(
            model_name='tripsearch',
            index=models.Index(fields=['start_city', 'end_city'], name='trip_search_start_c_2dd778_idx'),
        ),
        migrations.AddIndex(
            model_name='tripsearch',
            index=models.Index(fields=['session_id', '-created_at'], name='trip_search_session_e7e889_idx'),
        ),
        migrations.AddIndex(
            model_name='tripsearch',
            index=models.Index(fields=['-created_at'], name='trip_search_created_40d06a_idx'),
        ),
        migrations.AddIndex(
            model_name='tripitinerary',
            index=models.Index(fields=['search', 'rank'], name='trip_itiner_search__a1668a_idx'),
        ),
        migrations.AddIndex(
            model_name='tripitinerary',
            index=models.Index(fields=['search', 'optimization_type'], name='trip_itiner_search__15f808_idx'),
        ),
        migrations.AddIndex(
            model_name='tripitinerary',
            index=models.Index(fields=['-created_at'], name='trip_itiner_created_2e861a_idx'),
        ),
    ]
