# Generated by Django 6.0.2 on 2026-02-17 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('operator_type', models.CharField(choices=[('AIRLINE', 'Airline'), ('TRAIN', 'Train Operator'), ('BUS', 'Bus Operator'), ('FERRY', 'Ferry Operator')], max_length=50)),
                ('logo_url', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transport_operators',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('FLIGHT', 'Flight'), ('TRAIN', 'Train'), ('BUS', 'Bus'), ('FERRY', 'Ferry')], max_length=20)),
                ('route_code', models.CharField(blank=True, max_length=50)),
                ('origin_station', models.CharField(max_length=255)),
                ('destination_station', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_routes', to='destinations.city')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='transport.transportoperator')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_routes', to='destinations.city')),
            ],
            options={
                'db_table': 'transport_routes',
            },
        ),
        migrations.CreateModel(
            name='TransportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price in EUR', max_digits=10)),
                ('currency', models.CharField(default='EUR', help_text='ISO 4217 currency code', max_length=3)),
                ('departure_time', models.TimeField(help_text='Daily departure time')),
                ('arrival_time', models.TimeField(help_text='Daily arrival time')),
                ('duration_minutes', models.PositiveIntegerField()),
                ('operates_monday', models.BooleanField(default=True)),
                ('operates_tuesday', models.BooleanField(default=True)),
                ('operates_wednesday', models.BooleanField(default=True)),
                ('operates_thursday', models.BooleanField(default=True)),
                ('operates_friday', models.BooleanField(default=True)),
                ('operates_saturday', models.BooleanField(default=True)),
                ('operates_sunday', models.BooleanField(default=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('total_capacity', models.PositiveIntegerField(default=100)),
                ('remaining_capacity', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='transport.transportroute')),
            ],
            options={
                'db_table': 'transport_schedules',
                'ordering': ['departure_time'],
            },
        ),
        migrations.AddIndex(
            model_name='transportroute',
            index=models.Index(fields=['origin', 'destination', 'transport_type'], name='transport_r_origin__a3223e_idx'),
        ),
        migrations.AddIndex(
            model_name='transportroute',
            index=models.Index(fields=['is_active'], name='transport_r_is_acti_46ab94_idx'),
        ),
        migrations.AddIndex(
            model_name='transportroute',
            index=models.Index(fields=['operator', 'is_active'], name='transport_r_operato_b62b7a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transportroute',
            unique_together={('operator', 'origin', 'destination', 'route_code')},
        ),
        migrations.AddIndex(
            model_name='transportschedule',
            index=models.Index(fields=['route', 'departure_time'], name='transport_s_route_i_b0ed20_idx'),
        ),
        migrations.AddIndex(
            model_name='transportschedule',
            index=models.Index(fields=['valid_from', 'valid_until'], name='transport_s_valid_f_871b63_idx'),
        ),
        migrations.AddIndex(
            model_name='transportschedule',
            index=models.Index(fields=['is_active', 'base_price'], name='transport_s_is_acti_1990f3_idx'),
        ),
        migrations.AddIndex(
            model_name='transportschedule',
            index=models.Index(fields=['route', 'is_active', 'base_price'], name='transport_s_route_i_89b120_idx'),
        ),
    ]
