# Generated by Django 6.0.2 on 2026-02-17 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price in EUR', max_digits=10)),
                ('currency', models.CharField(default='EUR', help_text='ISO 4217 currency code', max_length=3)),
                ('departure_date', models.DateField(help_text='Departure date')),
                ('departure_time', models.TimeField(help_text='Departure time')),
                ('arrival_date', models.DateField(help_text='Arrival date')),
                ('arrival_time', models.TimeField(help_text='Arrival time')),
                ('total_travel_time', models.DurationField(help_text='Total travel time duration')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transport_travel_options',
                'ordering': ['departure_date', 'departure_time'],
            },
        ),
        migrations.RemoveIndex(
            model_name='transportschedule',
            name='transport_s_route_i_b0ed20_idx',
        ),
        migrations.RemoveIndex(
            model_name='transportschedule',
            name='transport_s_valid_f_871b63_idx',
        ),
        migrations.RemoveIndex(
            model_name='transportschedule',
            name='transport_s_is_acti_1990f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='transportschedule',
            name='transport_s_route_i_89b120_idx',
        ),
        migrations.AddField(
            model_name='traveloption',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_options', to='transport.transportroute'),
        ),
        migrations.RemoveField(
            model_name='transportschedule',
            name='route',
        ),
        migrations.AddIndex(
            model_name='traveloption',
            index=models.Index(fields=['route', 'departure_date'], name='transport_t_route_i_60d93e_idx'),
        ),
        migrations.AddIndex(
            model_name='traveloption',
            index=models.Index(fields=['departure_date', 'is_active'], name='transport_t_departu_c01794_idx'),
        ),
        migrations.DeleteModel(
            name='TransportSchedule',
        ),
    ]
